version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/doit/ # 인스턴스에서 파일이 저장될 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

# hooks:
#   AfterInstall:
#     - location: deploy.sh
#       timeout: 60
#       runas: root